readCell(Line, Col, BoardSize):-
    RealSize is BoardSize*2,
    read_line_to_codes(user_input, Codes),
    string_codes(String, Codes),
    atom_chars(String, Chars),
    nth0(0, Chars, LineChar),
    char_code(LineChar, LineNum),
    Line is LineNum-65,
    Line@>=0,
    Line@<RealSize,
    nth0(1, Chars, ColChar),
    atom_number(ColChar, ColNum),
    Col is ColNum - 1,
    Col@>=0,
    Col@<RealSize.